name: Print environment variable

on:
   workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true

jobs:    
  prod:
    runs-on: windows-latest
    steps:
      - name: Create Build Info File
        run: |
          echo "release_id=BBInforma_${{ github.run_id }}.zip" >> build-info.txt
          echo "Branch Name= ${{ GITHUB.REPOSITORY }}" >> build-info.txt
          echo "Branch Name= ${{ GITHUB.SHA }}" >> build-info.txt
          echo "Branch Name= ${{ GITHUB.RUN_NUMBER }}" >> build-info.txt

          Get-Content build-info.txt

          
