name: Print environment variable
on:
  push:
    branches:
      - "!main"
      - "!develop"
    tags: 
      - '*'
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true

jobs:    
  prod:
    runs-on: ubuntu-latest
    steps:
      - name: Create Build Info File
        run: |
          echo $Env:GITHUB_ENV


          
