name: Print environment variable
on:
  push:
    branches:
      - "!main"
      - "!develop"
    tags: 
      - '*'
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true

jobs:    
  prod:
    runs-on: ubuntu-latest
    steps:
      - name: Create Build Info File
        run: |
          echo ${{ env.environment }}
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

          
