name: 'custom GITHUB_ENV var Demo'

on:  workflow_dispatch

jobs:
  custom_GITHUB_ENV:
    runs-on: windows-latest
    steps:
    - name: Use the value
      id: step_two
      shell: cmd
      run: |
        FOR /F "tokens=* USEBACKQ" %%F IN (`chdir`) DO (SET var=%%F)
        ECHO %var%
        



        
