name: 'custom GITHUB_ENV var Demo'

on:  workflow_dispatch

jobs:
  custom_GITHUB_ENV:
    runs-on: windows-latest
    steps:
    - name: Use the value
      id: step_two
      shell: cmd
      run: |
         echo " manikName= ${{ GITHUB.WORKFLOW }}"
         $manikName


        
