name: Print environment variable

on:
   workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true

jobs:    
  prod:
    if: ${{ github.ref_name == 'release--test' || github.event.inputs.environment == 'PROD' }}
    env:
      environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}
        
  dev:
    if: ${{ github.ref_name == 'development' || github.event.inputs.environment == 'DEV' }}
    env:
      environment: DEV
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}
