name: Print environment variable

on:
   workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true

jobs:    
  prod:
    runs-on: windows-latest
    steps:
      - name: Create Build Info File
        if: ${{ github.event_name == 'push'|| ( github.event_name == 'workflow_run'&& github.event.workflow_run.conclusion == 'success') }}
        run: |
          echo ${{ env.environment }}
          echo "release_id=BBInforma_${{ github.run_id }}.zip" >> build-info.txt
          echo "Repo Name  Name= ${{ GITHUB.REPOSITORY }}" >> build-info.txt
          echo "Commit Id = ${{ GITHUB.SHA }}" >> build-info.txt
          echo "GITHUB RUN NUMBERe= ${{ GITHUB.RUN_NUMBER }}" >> build-info.txt
          echo "Branch Name= ${{ GITHUB.REF_NAME }}" >> build-info.txt
          echo " GITHUB ACTOR Name= ${{ GITHUB.ACTOR }}" >> build-info.txt
          Get-Content build-info.txt

          
