name: 'custom GITHUB_ENV var Demo'

on:  workflow_dispatch

jobs:
  custom_GITHUB_ENV:
    runs-on: windows-latest
    steps:
    - name: Use the value
      id: step_two
      shell: cmd
      run: |
        chdir_path1=chdir
         echo  ${{ GITHUB.REPOSITORY }}"
         echo "${{ GITHUB.WORKFLOW }}"
         echo "${{GITHUB_WORKSPACE }}"


        
