name: 'custom GITHUB_ENV var Demo'

on:  workflow_dispatch

jobs:
  custom_GITHUB_ENV:
    runs-on: windows-latest
    steps:
    - name: Set the value
      shell: cmd
      id: secret
      run: |
        chdir
        echo "test=$(chdir)" >> "$GITHUB_OUTPUT" 
        

    - name: Use the value
      id: step_two
      shell: cmd
      run: |
        echo "${{ env.action_state }}" # This will output 'yellow'
        echo "${{ env.chdir_path }}" # This will output 'yellow'
        echo "${{steps.secret.outputs.test}}"
