name: Print environment variable

on:
   workflow_dispatch:
    inputs:
      environment:
        type: string
        default: DEV
        required: true

jobs:    
  prod:
    runs-on: windows-latest
    steps:
      - name: Create Build Info File
        run: |
          echo "Repository = ${ GITHUB_REPOSITORY }" >> build-info.txt
          

          echo "Commit SHA= ${ GITHUB_SHA }" >> build-info.txt

          echo "Branch Name= ${ GITHUB_REF_NAME }" >> build-info.txt

          Get-Content build-info.txt

          
