name: choice Print environment variable

on:
   workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: DEV
        options:
          - 'DEV'
          - 'QA'
          - 'prod'
      Buildid:
        type: string
        required: true
        default: zipfilepath
jobs:    
  prod:
    if: ${{ github.ref_name == 'develop' || github.event.inputs.environment == 'PROD' }}
    env:
      environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}
  QA:
    if: ${{ github.ref_name == 'develop' || github.event.inputs.environment == 'QA' }}
    env:
      environment: QA
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: env
        
        
  dev:
    if: ${{ github.ref_name == 'develop' || github.event.inputs.environment == 'DEV' }}
    runs-on: windows-latest
    steps:
      - name: Print value
        run: env


   
