name: choice Print environment variable

on:
   workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: DEV
        options:
          - 'DEV'
          - 'QA'
          - 'prod'
      Buildid:
        type: string
        required: true
        default: zipfilepath
jobs:    
  prod:
    if: ${{ github.ref_name == 'develop' || github.event.inputs.environment == 'PROD' }}
    env:
      environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}
  QA:
    if: ${{ github.ref_name == 'develop' || github.event.inputs.environment == 'QA' }}
    env:
      environment: QA
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}
        
        
  dev:
    if: ${{ github.ref_name == 'develop' || github.event.inputs.environment == 'DEV' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ github.event.inputs.environment }}
      - name: Print value
        run: echo ${{ github.event.inputs.Buildid }}  > Buildid.txt
      - name: Print value 
        run: |
           ls -la
           pwd
           mkdir ~/dev
           echo ${{ github.event.inputs.Buildid }}  > ~/dev/Buildid.txt
           ls -la ~/dev/
           pwd
           cat ~/dev/Buildid.txt
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: 'dev'
          container_name: 'devcarelog'
          connection_string: 'sp=racwd&st=2023-09-27T13:20:10Z&se=2024-12-31T21:20:10Z&spr=https&sv=2022-11-02&sr=c&sig=6LqHiY5uIYLh6wwaNfVJv6qiTrM0enFKjnbp0%2BVT9Gk%3D'
          overwrite: 'true' 
      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ~/dev           
