name: choice Print environment variable

on:
   workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: DEV
        options:
          - 'DEV'
          - 'QA'
          - 'prod'
      Buildid:
        type: string
        required: true
        default: zipfilepath
jobs:    
  prod:
    if: ${{ github.ref_name == 'develop' || github.event.inputs.environment == 'PROD' }}
    env:
      environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}
  QA:
    if: ${{ github.ref_name == 'develop' || github.event.inputs.environment == 'QA' }}
    env:
      environment: QA
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: env
        
        
  dev:
    if: ${{ github.ref_name == 'develop' || github.event.inputs.environment == 'DEV' }}
    env:
      environment: DEV
    runs-on: windows-latest
    steps:
      - name: Set build version
        shell: pwsh
        run: |
          $date = Get-Date -Format "MMddyy"
          Write-Output "RELEASE_STRING=$date" >> $Env:GITHUB_ENV
          Write-Output "RELEASE_STRING=$date" >> $Env:GITHUB_ENV
          Write-Output "MAJOR=4" >> $Env:GITHUB_ENV
          Write-Output "MINOR=$($date.Substring(0,4))" >> $Env:GITHUB_ENV
          Write-Output "BUILD=$($date.Substring(4,2))" >> $Env:GITHUB_ENV
          Write-Output "REVISION=${{ GITHUB.RUN_NUMBER }}" >> $Env:GITHUB_ENV
          Write-Output "v${{ env.MAJOR }}.${{ env.MINOR }}${{ env.BUILD }}.${{ env.REVISION }}"


   
