name: choice Print environment variable

on:
   workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: DEV
        options:
          - 'DEV'
          - 'QA'
          - 'prod'
      Buildid:
        type: string
        required: true
        default: zipfilepath
jobs:    
  prod:
    if: ${{ github.ref_name == 'develop' || github.event.inputs.environment == 'PROD' }}
    env:
      environment: PROD
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}
  QA:
    if: ${{ github.ref_name == 'develop' || github.event.inputs.environment == 'QA' }}
    env:
      environment: QA
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ env.environment }}
        
        
  dev:
    if: ${{ github.ref_name == 'develop' || github.event.inputs.environment == 'DEV' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print value
        run: echo ${{ github.event.inputs.environment }}
      - name: Print value
        run: echo ${{ github.event.inputs.Buildid }}  > hw.txt
      - name: Print value 
        run: |
           ls -la
           mkdir ~/manik
           echo ${{ github.event.inputs.Buildid }}  > ~/manik/hw.txt
           ls -la ~/manik/
           cat ~/manik/hw.txt
      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ~/manik           
