name: BBInforma_webserver_test
on:
  push:
    branches:
      - "!main"
      - "!develop"
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
     inputs:
      artifact_name_zip:
        description: 'artifact_name_zip'
        required: true
        default: "BBInforma_${{ github.run_id }}.zip"
      test:
        description: "Test"
        required: true
        default: true
  
env:
  APP_NAME_ENV: BBInforma
  SOLUTION_FILE_PATH_ENV: WebApplications\BBInforma\BBInforma.vbproj
  SOURCE_PATH_ZIP_ENV: WebApplications/BBInforma/obj/Publish/*
  BLOB_PATH_TO_UPLOAD_ENV: BBI/pocdeployment

permissions:
  contents: read

jobs:
  build-app:
    if: "${{ github.event.inputs.test = '' }}"
    uses: ./.github/workflows/template-build-deploy.yml
    with:
      APP_NAME: "${{env.APP_NAME_ENV}}"
      SOLUTION_FILE_PAT: "${{env.SOLUTION_FILE_PATH_ENV}}"
      SOURCE_PATH_ZIP: "${{env.SOURCE_PATH_ZIP_ENV}}"
      ARTIFACT_NAME: "BBInforma_${{ github.run_id }}.zip"
      BLOB_PATH_TO_UPLOAD: "${{env.BLOB_PATH_TO_UPLOAD_ENV}}"
    secrets: inherit
    
  Dev-deploy-app:
    needs: build-app
    uses: ./.github/workflows/template-server-deploy.yml
    with:
      app_job_template: "bbinforma-web-deployments"
      limit: "sce1dvbbwb002"
      artifact_name: ${{ github.event.inputs.artifact_name_zip }}
      application_name: "bbiinforma"
      working_environment: development
    secrets: inherit
